-- MySQL Script generated by MySQL Workbench
-- Tue Jun 28 15:11:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_mercado_limpo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_mercado_limpo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_mercado_limpo` DEFAULT CHARACTER SET utf8 ;
USE `db_mercado_limpo` ;

-- -----------------------------------------------------
-- Table `db_mercado_limpo`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mercado_limpo`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mercado_limpo`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mercado_limpo`.`tb_categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mercado_limpo`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mercado_limpo`.`tb_produto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `preco` DECIMAL(9,2) NOT NULL,
  `estoque` INT NOT NULL,
  `usuario_id` BIGINT NULL,
  `categoria_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produto_tb_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_mercado_limpo`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `db_mercado_limpo`.`tb_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
